name: mothercare_mobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  build_runner: ^2.3.3

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  connectivity_plus: ^3.0.2
  google_fonts: ^4.0.4
  get_it: ^7.2.0
  dio: ^4.0.0
  retrofit: ^3.3.1
  retrofit_generator: ^4.0.1
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  auto_route: ^7.4.0
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  webview_flutter_plus: ^0.3.0+2
  shimmer: ^2.0.0
  rename: ^2.1.1
  file_picker: ^5.2.7
  pretty_dio_logger: ^1.1.1
  image_picker: ^0.8.8
  email_validator: ^2.1.16
  http_parser: ^4.0.2
  url_launcher: ^6.1.11
  moment_dart: ^0.17.4
  photo_view: ^0.14.0
  gallery_saver: ^2.3.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.0
  flutter_image_compress: ^2.0.3
  timeline_list: ^0.0.6
  flutter_html: 3.0.0-alpha.6
  flutter_inappwebview: ^5.7.2+3
  keyboard_dismisser: ^3.0.0
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.0

flutter_intl:
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/
    - assets/gif/
    - assets/jpg/
    - assets/web/
